@startuml

Class Mastermind
Class Square
Class isSuccessSquare
Class ProposedCombinationSection
Class isSuccessSection
Class SecretCombinationSection
Class ProposedCombinationAttempt
Class isSuccessAttempt
Class SecretPatron
Class ColorPin
Class isSuccessAttemptPin
Class Turn
Class Player
Class Color
Class MakerAction
Class BreakerAction
Class PutWhitePin
Class PutBlackPin

Class Red
Class Blue
Class Green
Class Yellow
Class Pink
Class White
Class Black
Class Brown


Mastermind *-- isSuccessSection
Mastermind *-- ProposedCombinationSection
Mastermind *-- SecretCombinationSection
Mastermind *--- "60" isSuccessAttemptPin
note on link
    x60 Black
    x60 White
end note

Mastermind *-- "192" ColorPin
note on link
   x24 Red
   x24 Blue
   x24 Green
   x24 Yellow
   x24 Pink
   x24 White
   x24 Black
   x24 Brown
end note
Mastermind *-- Turn
Mastermind *-- "2" Player
ColorPin o-- Color
Square o-- Color
Turn --> Player
ProposedCombinationSection *-- "12" ProposedCombinationAttempt
isSuccessSection *-- "12" isSuccessAttempt
isSuccessAttempt *-- "5" isSuccessSquare
ProposedCombinationAttempt *-- "5" Square
SecretCombinationSection *-- SecretPatron
SecretPatron *-- "5" Square
Maker --> SecretCombinationSection
Breaker --> ProposedCombinationSection
Maker --> isSuccessSection
Breaker ..> BreakerGoal
BreakerGoal ..> ProposedCombinationAttempt
BreakerGoal ....> SecretPatron

Maker ..> MakerAction
Breaker ...> BreakerAction

MakerAction ..> isSuccessAttempt
MakerAction ....> SecretPatron
MakerAction ....> isSuccessAttemptPin
'PutBlackPin ..> isSuccessAttemptPin
'PutWhitePin ..> isSuccessAttemptPin

Player <|-- Maker
Player <|-- Breaker

Color <|-- Red
Color <|-- Blue
Color <|-- Green
Color <|-- Yellow
Color <|-- Pink
Color <|-- White
Color <|-- Black
Color <|-- Brown

BreakerGoal <|-- SamePositionAndColor
BreakerGoal <|-- SameColorNotPosition
BreakerGoal <|-- WinTheGame


BreakerAction ..> ColorPin
BreakerAction ....> ProposedCombinationAttempt

MakerAction <|-- PutBlackPin
MakerAction <|-- PutWhitePin

Maker ..> MakerGoalWinTheGame
MakerGoalWinTheGame ...> ProposedCombinationSection

BreakerAction <|-- PutColorPin


@enduml